const CARTAS = [
  // COISAS
  ["ELEFANTE","grande","savana","mamute","circo","marfim"],
  ["PIZZA","mozzarella","forno","redonda","Itália","fatia"],
  ["GUITARRA","cordas","rock","instrumento","amplificador","solo"],
  ["AVIÃO","turbina","piloto","decolagem","voar","hangar"],
  ["CASTELO","torre","rei","medieval","fosso","pedra"],
  ["OCEANO","profundo","onda","marinheiro","salgado","abismo"],
  ["VAMPIRO","caixão","drácula","sangue","morcego","imortal"],
  ["FOGUETE","NASA","órbita","combustível","astronauta","lançamento"],
  ["BIBLIOTECA","livro","silêncio","estante","leitura","catalogar"],
  ["DINOSSAURO","jurássico","extinção","fóssil","réptil","T-Rex"],
  ["CHOCOLATE","cacau","Bélgica","doce","derretido","amargo"],
  ["MONTANHA","escalada","cume","neve","trilha","avalanche"],
  ["PIRATA","âncora","tesouro","caribe","navio","bandeira"],
  ["TARTARUGA","casco","lenta","marinha","réptil","longevidade"],
  ["SUBMARINO","imersão","periscópio","torpedo","profundeza","escotilha"],
  ["LABIRINTO","saída","minotauro","mapa","perdido","corredor"],
  ["BRUXA","vassoura","caldeirão","Halloween","feitiço","chapéu"],
  ["RELÓGIO","ponteiro","hora","alarme","quartzo","cuco"],
  ["CACHOEIRA","queda","córrego","arco-íris","pedra","salto"],
  ["FANTASMA","assombração","transparente","mansão","morte","aparição"],
  ["CIRCO","palhaço","trapézio","domador","lona","malabarismo"],
  ["NAVIO","âncora","proa","capitão","convés","carga"],
  ["DRAGÃO","fogo","escamas","fantasia","voar","princesa"],
  ["PIRÂMIDE","Egito","faraó","múmia","antigo","areia"],
  ["VULCÃO","lava","erupção","magma","cinzas","Vesúvio"],
  ["IGLU","neve","Inuit","gelo","ártico","esquimó"],
  ["GOLFINHO","mamífero","aquático","salto","inteligente","sonar"],
  ["LEÃO","juba","savana","rugido","rei","caça"],
  ["BORBOLETA","metamorfose","casulo","asa","flor","lepidoptera"],
  ["ESPELHO","reflexo","vidro","vaidade","imagem","mercúrio"],
  ["TESOURO","ouro","baú","mapa","pirata","riqueza"],
  ["FURACÃO","vento","olho","tempestade","destruição","categoria"],
  ["MICROSCÓPIO","lente","bactéria","laboratório","aumento","célula"],
  ["ARCO-ÍRIS","cor","luz","prisma","chuva","espectro"],
  ["POLVO","tentáculo","tinta","fundo-mar","camaleão","molusco"],
  ["TORNADO","vórtice","Kansas","destruição","funil","vento"],
  ["SUSHI","Japão","arroz","peixe","wasabi","rolo"],
  ["METRÔ","trilho","túnel","vagão","estação","urbano"],
  ["FLORESTA","árvore","fauna","flora","densa","trilha"],
  ["CACTO","espinho","deserto","água","seco","suculenta"],
  ["MÁGICO","truque","cartola","varinha","ilusão","palco"],
  ["TREM","locomotiva","trilho","estação","vagão","apito"],
  ["ESPADA","lâmina","batalha","cavaleiro","duelo","forja"],
  ["SAMURAI","katana","honra","Japão","armadura","bushido"],
  ["VIKING","barco","espada","Nórdico","raid","chifre"],
  ["ASTRONAUTA","espacial","NASA","órbita","capacete","gravidade"],
  ["PINGUIM","Antártica","gelo","marcha","gravata","nado"],
  ["GIRAFA","pescoço","África","alto","savana","manchas"],
  ["BALEIA","mamífero","oceano","migração","canto","azul"],
  ["ROBÔ","inteligência","metal","programação","futuro","humanoide"],
  ["LAREIRA","fogo","inverno","lenha","calor","chaminé"],
  ["FORMIGA","colônia","força","rainha","inseto","trabalho"],
  ["ABELHA","mel","colmeia","rainha","flores","ferroar"],
  ["LOBO","uivo","lua","matilha","floresta","predador"],
  ["CORVO","preto","Poe","inteligente","mau-agouro","voo"],
  ["CANGURU","marsupial","Austrália","bolsa","salto","cauda"],
  ["BICICLETA","pedal","roda","selim","corrente","parque"],
  ["CHAVE","tranca","ferreiro","segredo","abrir","cofre"],
  ["ÂNCORA","navio","fundo","peso","porto","marinha"],
  ["TACO","México","milho","recheio","pimenta","tortilha"],
  ["HAMBÚRGUER","carne","pão","queijo","fast-food","grelha"],
  ["SORVETE","gelado","cone","sabor","verão","cremoso"],
  ["CAFÉ","grão","aroma","espresso","manhã","barista"],
  ["CINEMA","filme","tela","pipoca","escuro","emoção"],
  ["PRAIA","areia","onda","guarda-sol","bronzeado","mar"],
  ["JARDIM","flor","solo","rega","borboleta","canteiro"],
  ["COZINHA","fogão","panela","chef","receita","tempero"],
  ["PISCINA","nadar","cloro","raia","borda","mergulho"],
  ["CHURRASQUEIRA","brasa","carne","fumaça","espeto","fim-de-semana"],
  ["MONSTRO","criatura","assustador","esconderijo","dentes","garra"],
  ["QUEIJO","Holanda","fermentação","leite","bolor","maturação"],
  ["BÚSSOLA","norte","sul","navegação","agulha","orientação"],
  ["FLAUTA","sopro","madeira","orquestra","nota","melodia"],
  ["COGUMELO","fungo","floresta","venenoso","chapéu","esporo"],
  ["FAROL","luz","costa","sinal","navegação","torre"],
  ["CACHORRO","cão","latido","pet","canil","coleira"],
  ["GATO","felino","miado","arranhar","bigodes","caçar"],
  ["LEÃO","selva","juba","rei","predador","alcateia"],
  ["TIGRE","listras","selvagem","felino","caçador","rugido"],
  ["URSO","hibernar","mel","floresta","peludo","grande"],
  ["CAVALO","crina","sela","galope","estábulo","rédea"],
  ["VACA","leite","fazenda","boi","pasto","ruminar"],
  ["OVELHA","lã","rebanho","pastoreio","ovelheiro","macia"],
  ["CABRA","chifre","leite","bode","montanha","rebanho"],
  ["PORCO","chiqueiro","toucinho","sujo","focinho","suíno"],
  ["GALINHA","ovo","galinheiro","pena","ciscar","ave"],
  ["PATO","lago","grasnar","pena","nadar","ave"],
  ["GALO","cantar","crista","amanhecer","galinheiro","ave"],
  ["PEIXE","nadar","aquático","escama","mar","brânquia"],
  ["TUBARÃO","predador","barbatana","oceano","dente","mar"],
  ["BALEIA","oceano","gigante","mamífero","mar","canto"],
  ["GOLFINHO","inteligente","salto","mar","mamífero","sonar"],
  ["MACACO","selva","banana","árvore","primata","pular"],
  ["GIRAFA","pescoço","savana","alta","mancha","herbívoro"],
  ["ZEBRA","listras","savana","equino","manada","preto"],
  ["CANGURU","marsupial","salto","austrália","bolsa","pular"],
  ["COELHO","cenoura","orelha","toca","fofo","pular"],
  ["RATO","roedor","esgoto","pequeno","roer","praga"],
  ["MORCEGO","noturno","voar","caverna","asa","mamífero"],
  ["CORUJA","noturna","olhos","sabedoria","ave","voar"],
  ["ÁGUIA","rapina","voo","garras","céu","predadora"],
  ["FALCÃO","rápido","caça","ave","voo","garras"],
  ["POMBO","praça","voar","cidade","ave","grão"],
  ["PAPAGAIO","fala","colorido","bico","ave","tropical"],
  ["PAVÃO","penas","cauda","colorido","exibir","ave"],
  ["PERU","aves","festa","pena","grande","fazenda"],
  ["ABELHA","mel","colmeia","zumbido","inseto","pólen"],
  ["FORMIGA","colônia","trabalho","inseto","pequena","trilha"],
  ["BORBOLETA","asas","colorida","metamorfose","voar","inseto"],
  ["MOSQUITO","picada","inseto","zumbido","noite","pernilongo"],
  ["ARANHA","teia","oito","inseto","veneno","perna"],
  ["ESCORPIÃO","veneno","pinça","deserto","perigo","cauda"],
  ["COBRA","veneno","réptil","rastejar","silvo","presa"],
  ["JACARÉ","pântano","réptil","dentes","água","predador"],
  ["CROCODILO","réptil","rio","mandíbula","predador","água"],
  ["LAGARTO","réptil","sol","cauda","rastejar","escama"],
  ["TARTARUGA","casco","lenta","réptil","mar","longeva"],
  ["SAPO","anfíbio","pular","brejo","coaxar","úmido"],
  ["RENA","neve","chifre","natal","trenó","frio"],
  ["ALCE","chifres","floresta","grande","norte","mamífero"],
  ["BISÃO","manada","pradaria","grande","chifre","mamífero"],
  ["LOBO","alcateia","uivo","selvagem","predador","noite"],
  ["RAPOSA","astuta","cauda","selva","predadora","vermelha"],
  ["HIENA","carniça","riso","savana","predadora","manada"],
  ["LEOPARDO","manchas","felino","árvore","predador","rápido"],
  ["PANTERA","negra","felino","silenciosa","predadora","selva"],
  ["MAMUTE","extinto","presas","gelo","gigante","pré-histórico"],
  ["DINOSSAURO","extinto","fóssil","jurássico","réptil","gigante"],
  ["ROBOT","máquina","automação","metal","programa","futuro"],
  ["COMPUTADOR","pc","teclado","monitor","processador","software"],
  ["CELULAR","smartphone","app","toque","ligação","portátil"],
  ["TELEFONE","ligação","discagem","aparelho","voz","linha"],
  ["TELEVISÃO","tela","canal","controle","imagem","vídeo"],
  ["RÁDIO","som","frequência","antena","música","transmissão"],
  ["CÂMERA","foto","lente","imagem","flash","gravar"],
  ["IMPRESSORA","papel","tinta","imprimir","documento","usb"],
  ["GELADEIRA","frio","cozinha","freezer","conservar","eletro"],
  ["FOGÃO","cozinha","boca","gás","panela","chama"],
  ["MICROONDAS","aquecer","rápido","cozinha","timer","forno"],
  ["LIQUIDIFICADOR","misturar","cozinha","lâmina","bebida","motor"],
  ["ASPIRADOR","poeira","limpeza","sucção","casa","aparelho"],
  ["CARRO","motor","roda","volante","estrada","veículo"],
  ["MOTO","capacete","duas","motor","velocidade","veículo"],
  ["BICICLETA","pedal","roda","ciclista","corrente","duas"],
  ["ÔNIBUS","passageiro","parada","transporte","urbano","coletivo"],
  ["TREM","trilho","vagão","estação","ferrovia","locomotiva"],
  ["AVIÂO","voar","asa","aeroporto","piloto","jato"],
  ["NAVIO","mar","porto","grande","tripulação","embarcação"],
  ["BARCO","remo","água","pequeno","navegar","embarcação"],
  ["SUBMARINO","profundo","oceano","imersão","naval","água"],
  ["FOGUETE","espaço","lançamento","propulsão","nasa","orbita"],
  ["SATÉLITE","orbita","espaço","comunicação","antena","artificial"],
  ["PLANETA","orbita","espaço","mundo","astronomia","esfera"],
  ["ESTRELA","brilho","céu","constelação","luz","espaço"],
  ["LUA","satélite","noite","crateras","céu","cheia"],
  ["SOL","estrela","luz","calor","dia","sistema"],
  ["NUVEM","céu","branca","chuva","algodão","tempo"],
  ["CHUVA","água","nuvem","tempo","gotejar","molhado"],
  ["TEMPESTADE","raio","trovão","vento","chuva","forte"],
  ["VENTO","brisa","ar","sopro","tempo","rajada"],
  ["NEVE","frio","branca","inverno","gelo","cair"],
  ["GELO","frio","congelado","água","cubo","gelado"],
  ["FOGO","chama","calor","queimar","fumaça","incêndio"],
  ["ÁGUA","líquido","beber","rio","mar","transparente"],
  ["TERRA","solo","planeta","chão","natureza","mundo"],
  ["AREIA","praia","grão","deserto","fina","duna"],
  ["PEDRA","rocha","dura","mineral","solo","pesada"],
  ["MONTANHA","alto","pico","rocha","neve","escalar"],
  ["RIO","água","corrente","margem","ponte","fluxo"],
  ["LAGO","água","calmo","margem","doce","natureza"],
  ["OCEANO","mar","profundo","água","onda","imenso"],
  ["FLORESTA","árvore","selva","verde","natureza","mata"],
  ["DESERTO","areia","seco","duna","calor","árido"],
  ["ILHA","mar","isolada","praia","terra","oceano"],
  ["CADEIRA","assento","pernas","encosto","madeira","sentar"],
  ["MESA","tampo","pernas","madeira","apoio","móvel"],
  ["SOFÁ","estofado","sala","conforto","almofada","sentar"],
  ["CAMA","colchão","travesseiro","quarto","dormir","lençol"],
  ["TRAVESSEIRO","macio","sono","cabeça","cama","conforto"],
  ["LENÇOL","cama","tecido","cobrir","quarto","sono"],
  ["COBERTOR","aquecimento","cama","frio","macio","dormir"],
  ["ARMÁRIO","guardar","portas","roupas","móvel","quarto"],
  ["GAVETA","puxador","guardar","móvel","compartimento","abrir"],
  ["ESPELHO","reflexo","vidro","imagem","banheiro","parede"],
  ["TOALHA","secagem","banho","tecido","água","corpo"],
  ["SABONETE","espuma","limpeza","banho","cheiro","higiene"],
  ["ESCOVA DE DENTES","higiene","cerdas","pasta","boca","escovar"],
  ["PASTA DE DENTES","menta","higiene","escovar","tubo","sorriso"],
  ["PENTE","cabelo","dentes","arrumar","plástico","pentear"],
  ["ESCOVA","cabelo","cerdas","pentear","beleza","fio"],
  ["RELÓGIO","tempo","ponteiros","pulso","horas","marcar"],
  ["DESPERTADOR","acordar","alarme","tempo","manhã","relógio"],
  ["CALCULADORA","conta","números","teclas","resultado","eletrônica"],
  ["CADERNO","folhas","anotar","papel","escola","escrever"],
  ["LIVRO","leitura","páginas","história","papel","capa"],
  ["CANETA","tinta","escrever","ponta","papel","azul"],
  ["LÁPIS","grafite","apontar","escrever","papel","madeira"],
  ["BORRACHA","apagar","erro","lápis","branca","corrigir"],
  ["APONTADOR","lápis","grafite","girar","afiado","escola"],
  ["MOCHILA","alças","carregar","escola","bolso","costas"],
  ["BOLSA","alça","guardar","acessório","carregar","moda"],
  ["CARTEIRA","dinheiro","cartões","bolso","documentos","couro"],
  ["CHAVE","abrir","porta","metal","fechadura","acesso"],
  ["CADEADO","trancar","segurança","chave","metal","fecho"],
  ["PORTA","entrada","maçaneta","abrir","fechar","madeira"],
  ["JANELA","vidro","abrir","luz","ventilar","parede"],
  ["CORTINA","tecido","janela","privacidade","sala","cobrir"],
  ["LÂMPADA","luz","iluminar","energia","soquete","brilho"],
  ["ABAJUR","luz","mesa","iluminação","quarto","decorar"],
  ["VENTILADOR","vento","hélice","refrescar","elétrico","ar"],
  ["AR-CONDICIONADO","frio","clima","refrigeração","controle","ambiente"],
  ["AQUECEDOR","calor","inverno","temperatura","elétrico","ambiente"],
  ["PANELA","cozinhar","metal","fogo","comida","cozinha"],
  ["FRIGIDEIRA","fritar","cabo","metal","cozinha","óleo"],
  ["PRATO","comida","louça","mesa","servir","redondo"],
  ["COPO","beber","vidro","líquido","água","recipiente"],
  ["XÍCARA","café","chá","alça","louça","bebida"],
  ["COLHER","talher","sopa","metal","comer","mesa"],
  ["GARFO","talher","dentes","comer","metal","mesa"],
  ["FACA","cortar","lâmina","cozinha","metal","fio"],
  ["GUARDA-CHUVA","chuva","proteger","água","abrir","cabo"],
  ["ÓCULOS","visão","lentes","armação","rosto","enxergar"],
  ["CONTROLE REMOTO","botões","tv","canal","pilhas","distância"],
  ["PILHA","energia","bateria","eletrônico","carga","pequena"],

  // PESSOAS
  ["NEYMAR","futebol","brasil","drible","psg","camisa10"],
  ["LIONEL MESSI","argentina","futebol","craque","barcelona","gols"],
  ["CRISTIANO RONALDO","portugal","futebol","cr7","gols","atacante"],
  ["PELÉ","rei","futebol","brasil","santos","lenda"],
  ["MICHAEL JORDAN","basquete","nba","chicago","air","lenda"],
  ["LEBRON JAMES","nba","basquete","lakers","rei","atleta"],
  ["SERENA WILLIAMS","tênis","grand slam","campeã","atleta","eua"],
  ["ROGER FEDERER","tênis","suíço","elegante","grand slam","lenda"],
  ["RAFAEL NADAL","tênis","saibro","espanha","lutador","grand slam"],
  ["AYRTON SENNA","formula1","brasil","piloto","lenda","corrida"],
  ["LEWIS HAMILTON","formula1","mercedes","campeao","velocidade","piloto"],
  ["TAYLOR SWIFT","cantora","pop","album","grammy","turne"],
  ["BEYONCE","diva","pop","grammy","show","cantora"],
  ["RIHANNA","barbados","pop","hit","cantora","fenty"],
  ["JUSTIN BIEBER","pop","cantor","canada","hit","fama"],
  ["ARIANA GRANDE","voz","pop","cantora","hit","diva"],
  ["ED SHEERAN","violao","pop","cantor","ruivo","hit"],
  ["EMINEM","rap","slimshady","detroit","letras","rapper"],
  ["BILLIE EILISH","alternativo","pop","cantora","grammy","jovem"],
  ["LADY GAGA","pop","extravagante","oscar","cantora","show"],
  ["BRAD PITT","ator","hollywood","oscar","filmes","galã"],
  ["LEONARDO DICAPRIO","ator","oscar","titanic","hollywood","filmes"],
  ["TOM CRUISE","ator","ação","missão","hollywood","estrela"],
  ["JOHNNY DEPP","ator","pirata","hollywood","filmes","estrela"],
  ["ROBERT DOWNEY JR","ator","marvel","homem de ferro","hollywood","estrela"],
  ["SCARLETT JOHANSSON","atriz","marvel","viúva negra","hollywood","estrela"],
  ["JENNIFER LAWRENCE","atriz","katniss","hollywood","jogos vorazes","estrela"],
  ["ANGELINA JOLIE","atriz","oscar","hollywood","ativista","estrela"],
  ["OPRAH WINFREY","tv","apresentadora","entrevista","midia","eua"],
  ["MARK ZUCKERBERG","facebook","meta","tecnologia","ceo","bilionario"],
  ["ELON MUSK","tesla","spacex","bilionario","tecnologia","empreendedor"],
  ["JEFF BEZOS","amazon","bilionario","ceo","negocios","tecnologia"],
  ["BILL GATES","microsoft","bilionario","tecnologia","filantropia","ceo"],
  ["STEVE JOBS","apple","iphone","inovacao","visionario","tecnologia"],
  ["DONALD TRUMP","presidente","eua","politica","empresario","midia"],
  ["BARACK OBAMA","presidente","eua","politica","discurso","lider"],
  ["JOE BIDEN","presidente","eua","politica","governo","lider"],
  ["VLADIMIR PUTIN","russia","presidente","politica","kremlin","lider"],
  ["PAPA FRANCISCO","vaticano","igreja","catolico","papa","religiao"],
  ["DALAI LAMA","budismo","lider","espiritual","tibete","paz"],
  ["GRETA THUNBERG","clima","ativista","ambiente","jovem","protesto"],
  ["NELSON MANDELA","apartheid","lider","africa","nobel","paz"],

  // BRASILEIROS
  ["RONALDINHO GAÚCHO","futebol","drible","sorriso","barcelona","brasil"],
  ["MARTA","futebol","rainha","seleção","gols","brasil"],
  ["ANITTA","cantora","pop","funk","hit","brasil"],
  ["IVETE SANGALO","cantora","axé","bahia","trio","energia"],
  ["LUÍSA SONZA","cantora","pop","hit","brasil","show"],
  ["PABLLO VITTAR","drag","pop","cantora","hit","brasil"],
  ["GUSTTAVO LIMA","sertanejo","cantor","buteco","hit","brasil"],
  ["ZECA PAGODINHO","samba","pagode","cantor","alegria","brasil"],
  ["ROBERTO CARLOS","cantor","rei","romântico","mpb","brasil"],
  ["CAETANO VELOSO","mpb","cantor","tropicalia","bahia","música"],
  ["GILBERTO GIL","mpb","cantor","bahia","ministro","música"],
  ["CHICO BUARQUE","mpb","compositor","letras","música","brasil"],
  ["FÁTIMA BERNARDES","tv","jornalista","apresentadora","globo","brasil"],
  ["WILLIAM BONNER","jornal","tv","globo","âncora","notícia"],
  ["SILVIO SANTOS","tv","apresentador","sbt","auditório","empresário"],
  ["LUCIANO HUCK","tv","apresentador","domingo","globo","família"],
  ["FAUSTÃO","tv","apresentador","domingo","bordão","auditório"],
  ["XUXA","rainha","baixinha","tv","infantil","apresentadora"],
  ["ANGÉLICA","tv","apresentadora","loira","domingo","fama"],
  ["ELIANA","tv","apresentadora","domingo","sbt","loira"],
  ["MAISA SILVA","atriz","apresentadora","jovem","tv","carisma"],
  ["BRUNA MARQUEZINE","atriz","novela","globo","fama","brasil"],
  ["GIOVANNA ANTONELLI","atriz","novela","delegada","globo","sucesso"],
  ["TAÍS ARAÚJO","atriz","novela","globo","protagonista","talento"],
  ["LÁZARO RAMOS","ator","cinema","tv","diretor","brasil"],
  ["WAGNER MOURA","ator","cinema","narcos","capitão","talento"],
  ["SELTON MELLO","ator","cinema","diretor","humor","brasil"],
  ["RODRIGO SANTORO","ator","hollywood","cinema","brasil","talento"],
  ["FERNANDA MONTENEGRO","atriz","oscar","teatro","lenda","brasil"],
  ["FERNANDA TORRES","atriz","cinema","tv","talento","brasil"],
  ["GLORIA PIRES","atriz","novela","globo","vilã","sucesso"],
  ["SUSANA VIEIRA","atriz","novela","globo","veterana","fama"],
  ["TONY RAMOS","ator","novela","globo","veterano","talento"],
  ["ANTONIO FAGUNDES","ator","novela","globo","veterano","sucesso"],
  ["CAUÃ REYMOND","ator","novela","galã","globo","fama"],
  ["REYNALDO GIANECCHINI","ator","novela","galã","globo","sucesso"],
  ["FELIPE NETO","youtuber","internet","vídeos","influencer","brasil"],
  ["WHINDERSson NUNES","humor","youtuber","standup","internet","piauí"],
  ["CARLINHOS MAIA","influencer","instagram","humor","internet","fama"],
  ["VIRGÍNIA","influencer","instagram","beleza","fama","brasil"],
  ["JULIETTE","bbb","cantora","influencer","campeã","brasil"],
  ["SABRINA SATO","tv","apresentadora","japonesa","carisma","fama"],
  ["ADRIANE GALISTEU","tv","apresentadora","loira","fama","brasil"],
  ["OTAVIANO COSTA","tv","apresentador","humor","entrevista","fama"],
  ["MARCOS MION","tv","apresentador","caldeirão","globo","carisma"],
  ["TITE","técnico","futebol","seleção","treinador","brasil"],
  ["PAULO GUEDES","economia","ministro","governo","liberal","brasil"],
  ["SÉRGIO MORO","juiz","política","lava jato","ministro","brasil"],
  ["ALEXANDRE DE MORAES","stf","ministro","justiça","brasil","tribunal"],

  // PERSONAGENS
  ["BATMAN","gotham","cavaleiro","morcego","wayne","dc"],
  ["SUPERMAN","krypton","voar","heroi","clark","dc"],
  ["HOMEM-ARANHA","teia","aranha","peter","marvel","heroi"],
  ["HULK","verde","força","esmagar","banner","marvel"],
  ["HARRY POTTER","hogwarts","varinha","bruxo","magia","cicatriz"],
  ["DARTH VADER","sith","força","império","máscara","star wars"],
  ["LUKE SKYWALKER","jedi","força","sabreluz","rebeldes","star wars"],
  ["YODA","jedi","mestre","força","pequeno","star wars"],
  ["SHERLOCK HOLMES","detetive","lupa","mistério","watson","londres"],
  ["HOMER SIMPSON","donuts","cerveja","springfield","preguiça","simpsons"],
  ["BART SIMPSON","travesso","skate","springfield","aprontar","simpsons"],
  ["MICKEY MOUSE","disney","rato","orelhas","desenho","clássico"],
  ["MINNIE MOUSE","laço","disney","rato","namorada","clássica"],
  ["PATO DONALD","irritado","disney","marinheiro","pato","desenho"],
  ["ELSA","gelo","frozen","rainha","magia","disney"],
  ["ANNA","frozen","irmã","coragem","disney","princesa"],
  ["HOMEM DE FERRO","armadura","tony","stark","marvel","tecnologia"],
  ["CAPITÃO AMÉRICA","escudo","soldado","steve","marvel","herói"],
  ["THOR","martelo","asgard","deus","relâmpago","marvel"],
  ["LOKI","trapaça","asgard","vilao","marvel","deus"],
  ["WOLVERINE","garras","xmen","logan","cura","marvel"],
  ["DEADPOOL","tagarela","antiheroi","marvel","piada","vermelho"],
  ["KRATOS","espartano","deus","lâminas","vingança","playstation"],
  ["MARIO","nintendo","bigode","encanador","pular","cogumelo"],
  ["LUIGI","irmão","verde","nintendo","fantasma","mario"],
  ["SONIC","veloz","ouriço","anéis","sega","corrida"],
  ["ZELDA","princesa","hyrule","nintendo","reino","zelda"],
  ["PIKACHU","pokemon","raio","amarelo","fofo","ash"],
  ["GOKU","sayajin","dragonball","luta","kamehameha","anime"],
  ["VEGETA","orgulho","sayajin","dragonball","príncipe","anime"],
  ["NARUTO","ninja","hokage","anime","raposa","konoha"],
  ["ARAGORN","anel","gondor","rei","espada","lotr"],
  ["LEGOLAS","elfo","arco","anel","lotr","floresta"],
  ["GANDALF","mago","anel","cinzento","lotr","bastão"],
  ["FRODO","anel","hobbit","condado","missão","lotr"],
  ["SAMWISE","amizade","hobbit","frodo","leal","lotr"],
  ["JAMES BOND","007","espião","mi6","missão","agente"],
  ["INDIANA JONES","arqueólogo","chicote","aventura","tesouro","filme"],
  ["JACK SPARROW","pirata","caribe","rum","capitão","navio"],
  ["HANNIBAL LECTER","psiquiatra","canibal","silêncio","vilão","filme"],

  // PERSONAGENS BRASILEIROS
  ["ODETE ROITMAN","vilã","novela","rica","vale tudo","globo"],
  ["CARMINHA","vilã","avenida brasil","megera","tufão","globo"],
  ["NINA","vingança","avenida brasil","chef","protagonista","globo"],
  ["TUFÃO","futebol","avenida brasil","ingênuo","carminha","globo"],
  ["JADE","clone","novela","marrocos","romance","globo"],
  ["VIÚVA PORCINA","roque santeiro","novela","loira","sucesso","globo"],
  ["ROQUE SANTEIRO","herói","novela","cidade","mito","globo"],
  ["NAZARÉ TÉDESCO","vilã","senhora do destino","louca","meme","globo"],
  ["MARIA DO BAIRRO","sofrida","novela","amor","pobre","drama"],
  ["JOÃO GRILO","auto da compadecida","esperto","nordeste","humor","filme"],
  ["CHICÓ","auto da compadecida","medroso","amigo","humor","filme"],
  ["CAPITÃO NASCIMENTO","tropa de elite","bope","policial","missão","filme"],
  ["CRÔ","fina estampa","mordomo","humor","novela","globo"],
  ["PEREIRINHA","fina estampa","marinheiro","novela","família","globo"],
  ["TÔTA","cheias de charme","empreguete","novela","música","globo"],
  ["ROSÁRIO","cheias de charme","empreguete","cantora","novela","globo"],

  // ABSTRATOS
  ["AMOR","carinho","paixão","afeto","romance","coração"],
  ["FELICIDADE","alegria","sorriso","bem-estar","euforia","contentamento"],
  ["TRISTEZA","lágrimas","melancolia","dor","solidão","abatimento"],
  ["RAIVA","ódio","fúria","irritação","explosão","nervosismo"],
  ["MEDO","pavor","ansiedade","terror","insegurança","apreensão"],
  ["ESPERANÇA","fé","otimismo","futuro","confiança","luz"],
  ["SAUDADE","lembrança","nostalgia","ausência","afeto","memória"],
  ["ANSIEDADE","inquietação","tensão","preocupação","nervosismo","pressa"],
  ["PAZ","calma","serenidade","tranquilidade","harmonia","silêncio"],
  ["LIBERDADE","autonomia","independência","livre","escolha","voar"],
  ["CORAGEM","bravura","ousadia","força","determinação","enfrentar"],
  ["VERGONHA","constrangimento","timidez","culpa","exposição","embaraço"],
  ["CULPA","remorso","arrependimento","peso","erro","consciência"],
  ["ORGULHO","satisfação","autoestima","vaidade","honra","ego"],
  ["INVEJA","ciúme","comparação","desejo","ressentimento","cobiça"],
  ["CIÚME","posse","insegurança","desconfiança","relacionamento","medo"],
  ["SOLIDÃO","isolamento","silêncio","vazio","tristeza","ausência"],
  ["EMPATIA","compreensão","sensibilidade","apoio","cuidado","conexão"],
  ["GRATIDÃO","agradecimento","reconhecimento","apreço","bondade","retorno"],
  ["ADMIRAÇÃO","respeito","encanto","apreço","estima","inspiração"],
  ["DESEJO","vontade","impulso","anseio","atração","querer"],
  ["PAIXÃO","intensidade","amor","fogo","emoção","entrega"],
  ["TÉDIO","monotonia","cansaço","desinteresse","rotina","apatia"],
  ["ALÍVIO","descanso","relaxamento","peso","tranquilidade","respiro"],
  ["EUFORIA","êxtase","alegria","pico","entusiasmo","vibração"],
  ["SERENIDADE","calma","paz","equilíbrio","suavidade","quietude"],
  ["ANGÚSTIA","aflição","aperto","ansiedade","dor","sofrimento"],
  ["ENCANTAMENTO","magia","fascínio","maravilha","deslumbre","beleza"],
  ["CONFUSÃO","dúvida","desordem","incerteza","mente","caos"],
  ["HARMONIA","equilíbrio","acordo","paz","união","sintonia"],

  // PAÍSES
  ["BRASIL","américa","futebol","samba","Brasília","português"],
  ["ESTADOS UNIDOS","américa","dólar","washington","hollywood","inglês"],
  ["CANADÁ","américa","frio","maple","ottawa","inglês"],
  ["MÉXICO","américa","tacos","espanhol","cidade do méxico","sombrero"],
  ["ARGENTINA","américa","tango","buenos aires","espanhol","futebol"],
  ["REINO UNIDO","europa","londres","inglês","rainha","ilha"],
  ["FRANÇA","europa","paris","torre eiffel","francês","vinho"],
  ["ALEMANHA","europa","berlim","euro","alemão","indústria"],
  ["ITÁLIA","europa","roma","pizza","italiano","coliseu"],
  ["ESPANHA","europa","madrid","espanhol","tourada","flamenco"],
  ["PORTUGAL","europa","lisboa","português","fado","atlântico"],
  ["HOLANDA","europa","amsterdã","moinhos","tulipas","bicicleta"],
  ["BÉLGICA","europa","bruxelas","chocolate","euro","wafle"],
  ["SUÍÇA","europa","alpes","relógio","canivete","alpes"],
  ["SUÉCIA","europa","estocolmo","nórdico","frio","vikings"],
  ["NORUEGA","europa","fiordes","nórdico","oslo","frio"],
  ["RÚSSIA","europa","moscou","rúblo","frio","gigante"],
  ["CHINA","ásia","pequim","mandarim","muralha","população"],
  ["JAPÃO","ásia","tóquio","sushi","tecnologia","yen"],
  ["CORÉIA DO SUL","ásia","seul","kpop","samsung","coreano"],
  ["ÍNDIA","ásia","nova delhi","hinduísmo","população","rúpee"],
  ["INDONÉSIA","ásia","jacarta","ilhas","tropical","rupia"],
  ["ARÁBIA SAUDITA","ásia","petróleo","riade","deserto","árabe"],
  ["ISRAEL","ásia","jerusalém","hebraico","tecnologia","palestina"],
  ["EGITO","áfrica","cairo","pirâmides","nilo","árabe"],
  ["ÁFRICA DO SUL","áfrica","pretória","apartheid","rand","safári"],
  ["NIGÉRIA","áfrica","abuja","petróleo","população","africano"],
  ["AUSTRÁLIA","oceania","canguru","sydney","inglês","ilha"],
  ["NOVA ZELÂNDIA","oceania","wellington","kiwi","ilhas","inglês"],
  ["TURQUIA","implante","ancara","istambul","lira","eurásia"],
];